/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as GameIdIndexRouteImport } from './routes/game.$id/index'
import { Route as GameIdRecipesIndexRouteImport } from './routes/game.$id/recipes.index'
import { Route as GameIdItemsIndexRouteImport } from './routes/game.$id/items.index'
import { Route as GameIdInventoriesIndexRouteImport } from './routes/game.$id/inventories.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdIndexRoute = GameIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameIdRoute,
} as any)
const GameIdRecipesIndexRoute = GameIdRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => GameIdRoute,
} as any)
const GameIdItemsIndexRoute = GameIdItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => GameIdRoute,
} as any)
const GameIdInventoriesIndexRoute = GameIdInventoriesIndexRouteImport.update({
  id: '/inventories/',
  path: '/inventories/',
  getParentRoute: () => GameIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/game/$id/': typeof GameIdIndexRoute
  '/game/$id/inventories/': typeof GameIdInventoriesIndexRoute
  '/game/$id/items/': typeof GameIdItemsIndexRoute
  '/game/$id/recipes/': typeof GameIdRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$id': typeof GameIdIndexRoute
  '/game/$id/inventories': typeof GameIdInventoriesIndexRoute
  '/game/$id/items': typeof GameIdItemsIndexRoute
  '/game/$id/recipes': typeof GameIdRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/game/$id/': typeof GameIdIndexRoute
  '/game/$id/inventories/': typeof GameIdInventoriesIndexRoute
  '/game/$id/items/': typeof GameIdItemsIndexRoute
  '/game/$id/recipes/': typeof GameIdRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game/$id'
    | '/game/$id/'
    | '/game/$id/inventories/'
    | '/game/$id/items/'
    | '/game/$id/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game/$id'
    | '/game/$id/inventories'
    | '/game/$id/items'
    | '/game/$id/recipes'
  id:
    | '__root__'
    | '/'
    | '/game/$id'
    | '/game/$id/'
    | '/game/$id/inventories/'
    | '/game/$id/items/'
    | '/game/$id/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameIdRoute: typeof GameIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id/': {
      id: '/game/$id/'
      path: '/'
      fullPath: '/game/$id/'
      preLoaderRoute: typeof GameIdIndexRouteImport
      parentRoute: typeof GameIdRoute
    }
    '/game/$id/recipes/': {
      id: '/game/$id/recipes/'
      path: '/recipes'
      fullPath: '/game/$id/recipes/'
      preLoaderRoute: typeof GameIdRecipesIndexRouteImport
      parentRoute: typeof GameIdRoute
    }
    '/game/$id/items/': {
      id: '/game/$id/items/'
      path: '/items'
      fullPath: '/game/$id/items/'
      preLoaderRoute: typeof GameIdItemsIndexRouteImport
      parentRoute: typeof GameIdRoute
    }
    '/game/$id/inventories/': {
      id: '/game/$id/inventories/'
      path: '/inventories'
      fullPath: '/game/$id/inventories/'
      preLoaderRoute: typeof GameIdInventoriesIndexRouteImport
      parentRoute: typeof GameIdRoute
    }
  }
}

interface GameIdRouteChildren {
  GameIdIndexRoute: typeof GameIdIndexRoute
  GameIdInventoriesIndexRoute: typeof GameIdInventoriesIndexRoute
  GameIdItemsIndexRoute: typeof GameIdItemsIndexRoute
  GameIdRecipesIndexRoute: typeof GameIdRecipesIndexRoute
}

const GameIdRouteChildren: GameIdRouteChildren = {
  GameIdIndexRoute: GameIdIndexRoute,
  GameIdInventoriesIndexRoute: GameIdInventoriesIndexRoute,
  GameIdItemsIndexRoute: GameIdItemsIndexRoute,
  GameIdRecipesIndexRoute: GameIdRecipesIndexRoute,
}

const GameIdRouteWithChildren =
  GameIdRoute._addFileChildren(GameIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameIdRoute: GameIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
